server:
  port: ${APP_EXTERNAL_PORT}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
spring:
  application:
    name: ${APP_NAME}
  datasource:
    url: jdbc:postgresql://${HOSTNAME}:${DB_EXTERNAL_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${HOSTNAME}
    port: ${RABBITMQ_EXTERNAL_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        default-requeue-rejected: false
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
          multiplier: 2

